Feature/storage interface
eclipse-basyx/basyx-java-sdk pull request #234
Opened 2023-03-01 17:47 UTC by jannisjung

2023-03-02 13:51 UTC, Daespen commented on src/main/java/org/eclipse/basyx/aas/metamodel/map/descriptor/AASDescriptor.java
> +	public static AASDescriptor createAsFacade(Map<String, Object> map) {
Javadocs

2023-03-02 13:52 UTC, Daespen commented on src/main/java/org/eclipse/basyx/extensions/storage/IBaSyxStorageAPI.java
> +	T createOrUpdate(T obj);
public

2023-03-06 10:56 UTC, FrankSchnicke requested changes

2023-03-06 10:56 UTC, FrankSchnicke commented on src/main/java/org/eclipse/basyx/extensions/storage/BaSyxStorageAPI.java
> +	 * Retrieves an object by it's key from the persistence storage.
Typo "it's" should be "its

2023-03-07 06:57 UTC, FrankSchnicke approved these changes

2023-03-07 07:21 UTC, merged