Implement feature of enabling/disabling Observables
eclipse-basyx/basyx-java-sdk pull request #378
Opened 2023-12-05 14:10 UTC by mateusmolina-iese

2023-12-13 11:45 UTC, mateusmolina-iese commented on src/main/java/org/eclipse/basyx/submodel/aggregator/observing/ObservableSubmodelAggregatorV2.java
>  	public void createSubmodel(ISubmodelAPI submodelAPI) {
Remove method

2023-12-13 12:52 UTC, mdanish98 requested changes
Following are the very minor remarks.

2023-12-13 12:52 UTC, mdanish98 commented on src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/aggregator/mqtt/TestMqttV2SubmodelAggregatorObserver.java
> +	public void testCreateSubmodelViaApi() {
It would be better to rename this test method such that the below comment is not required, for e.g., noEventExpectedWhenSubmodelIsCreatedViaAPI

2023-12-13 12:52 UTC, mdanish98 commented on src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/aggregator/mqtt/TestMqttV2SubmodelAggregatorObserver.java
> +	private static Submodel createTestSubmodel() {
Please consider adding some vertical spacing in this method (line 190 ~ 196).

2023-12-14 08:04 UTC, mdanish98 approved these changes
Approved, @FrankSchnicke please approve the CI pipeline run.

2023-12-14 08:15 UTC, merged